# Generated by Django 3.2.5 on 2021-07-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210715_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='media_type',
            new_name='mediatype',
        ),
    ]
