# Generated by Django 3.2.5 on 2021-07-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
    ]
